copyright: !ENV [COPYRIGHT, "Copyright &copy; 2005-2022 Zenoss Inc."]
edit_uri: !ENV [EDIT_URI, ""]
extra_css:
  - css/lightbox.min.css
  - css/zenoss.css
extra_javascript:
  - js/jquery-3.6.0.min.js
  - js/lightbox.min.js
  - js/lightbox-options.js
  - https://unpkg.com/@popperjs/core@2
  - https://unpkg.com/tippy.js@6
  - js/config-tippy.js
extra:
  generator: false
  social: true
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx_zenoss.glossary
  - pymdownx_zenoss.lightbox
plugins:
  - include-markdown
  - literate-nav:
      nav_file: NAVIGATION.md
  - render_swagger
  - search
  - section-index
repo_name: !ENV [REPO_NAME, ""]
repo_url: !ENV [REPO_URL, ""]
site_name: !ENV [SITE_NAME, "Zenoss Cloud Documentation"]
site_url: !ENV [SITE_URL, ""]
theme:
  name: material
  favicon: /images/favicon.png
  logo_light_mode: /images/zenoss-logo-tag-black.png
  logo_dark_mode: /images/zenoss-logo-tag-white.png
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  custom_dir: overrides
use_directory_urls: false

### NOTE: Navigation has been moved to the "docs/NAVIGATION.md" file.  ###
###       See https://oprypin.github.io/mkdocs-literate-nav/index.html ###
###       for more information.                                        ###
